repos:
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3.13
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.15.0"
    hooks:
      - id: ruff
